name: CI
on:
  push:
    branches:
      - "main"
      - "demo"
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v3

      - name: SETUP NODE
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: SETUP YARN
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: INSTALL DEPENDENCIES
        run: yarn install --frozen-lockfile

      - name: RUN LINT
        run: yarn lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v3

      - name: SETUP NODE
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: SETUP YARN
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: INSTALL DEPENDENCIES
        run: yarn install --frozen-lockfile

      - name: RUN TYPECHECK
        run: yarn typecheck

  build:
    name: Build
    needs: [lint, typecheck]
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v3

      - name: SETUP NODE
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: SETUP YARN
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: INSTALL DEPENDENCIES
        run: yarn install --frozen-lockfile

      - name: RUN BUILD
        run: yarn build
